nmap <C-S-tab>       :tabprevious <CR>
map  <C-S-tab>       :tabprevious <CR>
imap <C-S-tab> <Esc> :tabprevious <CR>i
map  <S-W>           :tabclose    <CR>
nmap <C-tab>         :tabnext     <CR>
map  <C-tab>         :tabnext     <CR>
imap <C-tab>   <Esc> :tabnext     <CR>i
set guitablabel=%t
